#!/usr/bin/env bash
phalcon model _db_update
phalcon model algorithm_usage
phalcon model assessment
phalcon model assessment_response
phalcon model instrument
phalcon model instrument_schedule
phalcon model instrument_schedule_operation
phalcon model member_badge
phalcon model member_note
phalcon model message
phalcon model message_provider
phalcon model module
phalcon model operation
phalcon model organization_outcome
phalcon model outcome
phalcon model outcome_alignment
phalcon model outcome_event
phalcon model plan_item
phalcon model plan_item_status
phalcon model question
phalcon model question_choice
phalcon model question_group
phalcon model question_type
phalcon model recommendation
phalcon model relationship
phalcon model relationship_type
phalcon model resource_alignment
phalcon model resource_type
